### PR TITLE
Sanitize Add New Queue form input

### PR DESCRIPTION
**Pull request by sebastian-j-ibanez**
Sanitize form input on the Administration -> Labs/Inbox -> Add New Queue form.

### CODE REVIEW

**Review by yingbull — CHANGES_REQUESTED** [review]
Code looks good, Seb - but I think the pull request is a bit verbose with the commits and merge messages?  I think if you pulled down a branch of bullfrog and then cherry picked these over, for example, the pull request you send up would just be the commit of the change?  Just want to try and keep the git log as sanitary as we can...

**Comment by yingbull** [comment]
Also, I think you and Erin touched some of the same files (but not all in the same way), so if you could fix the merge along with getting the clean commits/etc in the pull request, that would be great.

**Comment by yingbull** [comment]
@sebastian-j-ibanez  can you follow up on this one, Thursday?

**Comment by sebastian-j-ibanez** [comment]
Yes, I will fix the commit history tomorrow.

**Comment by sebastian-j-ibanez** [comment]
> Also, I think you and Erin touched some of the same files (but not all in the same way), so if you could fix the merge along with getting the clean commits/etc in the pull request, that would be great.

Yeah there was overlap, but only on line 95.

Everything else in my PR is unique.

**Review by yingbull — APPROVED** [review]

**Pull request merged**
