### PR TITLE
Spring-hibernate-alpha-0.60

### PR DESCRIPTION
**Pull request by Wrekky**
Master Issue:
ASOS-61: Fixed the 500 error caused when clicking 'Submit' button on the Create Lab page under Inbox tab on the Main page nav bar.

QA Issue:
ASOS-158, 161, 162, 164, 166.
ASOS-151 - Soap Fixes.

### CODE REVIEW

**Review by yingbull — CHANGES_REQUESTED** [review]
This will give the impression to the user the task worked even if it puts a log message.  This is not the direction to fix the issue with the blank lab values, and working on that is out of scope right now.   Please remove this commit from the pull request in order for this to be approved; no further work on this item is needed at this time.   @Wrekky @kateyang1998

**Comment by kateyang1998** [comment]
Reverted the commit and merge the updated issue_main branch to the develop branch.

**Comment by yingbull** [comment]
The lab code with the issue is still showing here.   I am going to close this pull request, it will not be proceeded with due to the issue with the submitted code.   Resubmit for approval.

**Comment by yingbull** [comment]
Resubmit a pull request with the code at issue with the lab changes.

**Pull request closed without merging**
